[package]
name = "aviutl2-cli"
version = "0.3.0"
edition = "2024"
authors = ["Nanashi. <sevenc7c.com>"]
license = "MIT"
description = "AviUtl2のプラグイン・スクリプト開発に便利なコマンドラインツール"
repository = "https://github.com/sevenc-nanashi/aviutl2-cli"

[[bin]]
name = "au2"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.56", features = ["derive"] }
env_logger = "0.11.8"
fs-err = "3.2.2"
log = "0.4.29"
pathdiff = "0.2.3"
serde = { version = "1.0.228", features = ["derive"] }
toml = "0.9.11"
ureq = "3.1.4"
walkdir = "2.5.0"
zip = "7.2.0"

[dev-dependencies]
assert_cmd = "2.0.16"
predicates = "3.1.3"
tempfile = "3.14.0"
