name: Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release"
        required: true

jobs:
  bump-version:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.set_version.outputs.new_version }}
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Rust
        shell: bash
        run: |
          rustup toolchain install --profile minimal

      - name: Set up cargo-binstall
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-binstall

      - name: Set up mise
        uses: jdx/mise-action@v3
        with:
          install: true
          experimental: true

      - name: Set version
        id: set_version
        run: |
          cargo set-version ${{ github.event.inputs.version }}
          echo "new_version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT

      - name: Commit version bump
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -am "release: v${{ steps.set_version.outputs.new_version }}"
          git tag ${{ steps.set_version.outputs.new_version }}
          git push origin HEAD --tags

  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            prefix: -windows
          - os: ubuntu-latest
            prefix: -linux
    needs: bump-version
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          submodules: "recursive"
          ref: refs/tags/${{ github.event.inputs.version }}

      - name: Set up Rust
        shell: bash
        run: |
          rustup toolchain install --profile minimal

      - name: Cache rust
        uses: Swatinem/rust-cache@v2

      - name: Set up cargo-binstall
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-binstall

      - name: Set up mise
        uses: jdx/mise-action@v3
        with:
          install: true
          experimental: true

      - name: Prepare release
        shell: bash
        id: prepare
        run: |
          cargo build -r
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            cp target/release/au2.exe ./target/au2-v${{ github.event.inputs.version }}-windows.exe
            echo "au2_path=./target/au2-v${{ github.event.inputs.version }}-windows.exe" >> $GITHUB_OUTPUT
          else
            cp target/release/au2 ./target/au2-v${{ github.event.inputs.version }}-linux
            echo "au2_path=./target/au2-v${{ github.event.inputs.version }}-linux" >> $GITHUB_OUTPUT
          fi

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version }}
          fail_on_unmatched_files: true
          files: |
            ${{ steps.prepare.outputs.au2_path }}
  publish:
    needs: build
    runs-on: ubuntu-latest
    environment: publish
    permissions:
      contents: write
      packages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          submodules: "recursive"
          ref: refs/tags/${{ github.event.inputs.version }}

      - name: Set up Rust
        shell: bash
        run: |
          rustup toolchain install --profile minimal

      - name: Set up cargo-binstall
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-binstall

      - name: Set up mise
        uses: jdx/mise-action@v3
        with:
          install: true
          experimental: true

      - name: Login to crates.io
        uses: rust-lang/crates-io-auth-action@v1
        id: crates-io-auth

      - name: Publish to crates.io
        run: |
          cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.crates-io-auth.outputs.token }}
